# Require Drop All Capabilities
# FedRAMP 20x KSI Alignment:
# - KSI-CNA-02: Minimize attack surface and lateral movement potential
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-drop-all-capabilities
  annotations:
    policies.kyverno.io/title: Require Drop All Capabilities
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Capabilities permit privileged actions without giving full root access.
      This policy ensures that all capabilities are dropped.
      Aligns with FedRAMP 20x KSI-CNA-02: Minimize attack surface.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: NotEquals
            value: DELETE
      validate:
        message: >-
          Containers must drop all capabilities. Set securityContext.capabilities.drop
          to include 'ALL'. (KSI-CNA-02)
        foreach:
          - list: request.object.spec.[initContainers, containers][]
            deny:
              conditions:
                all:
                  - key: ALL
                    operator: AnyNotIn
                    value: "{{ element.securityContext.capabilities.drop[] || `[]` }}"
