# Infrastructure Kustomization for Staging
# FedRAMP 20x KSI Alignment:
# - KSI-SVC-04: Automated infrastructure configuration
# - KSI-CMT-02: Immutable infrastructure deployments
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging
  prune: true
  wait: true
  # Health checks ensure infrastructure is ready
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
  # Post-build variable substitution for environment-specific values
  postBuild:
    substitute:
      ENVIRONMENT: staging
      CLUSTER_NAME: fedramp-demo-staging
