# Flux Notifications - GitOps Event Alerting
# Aligns with: KSI-CMT-01 (Log and monitor all service modifications)
#              KSI-AFR-09 (Persistently validate security decisions)
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  type: alertmanager
  address: http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093/api/v2/alerts
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-reconciliation-alerts
  namespace: flux-system
spec:
  providerRef:
    name: alertmanager
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRepository
      name: '*'
  summary: "Flux reconciliation failure detected"
---
# Alert for all Flux events (info level for audit trail)
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-audit-trail
  namespace: flux-system
spec:
  providerRef:
    name: alertmanager
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
  inclusionList:
    - ".*Reconciliation finished.*"
    - ".*applied.*"
  summary: "Flux deployment activity"
